export default {
  "avatar": "",
  "balance": 0, // 钱包金额
  "brand_member_new": 0,
  "columns": [
    {
      "badge_color": "ff3618",
      "badge_name": "NEW",
      "description": "免费领百元红包",
      "device": 2,
      "end_time": 0,
      "image_hash": "b95dce0c02567eb9bc185485f93e1719png",
      "is_show": 1,
      "key": "credit",
      "name": "饿了么联名卡",
      "schema": "eleme://web?url=https%3A%2F%2Fh5.ele.me%2Fcreditcard%2F%23from%3Dprofile",
      "start_time": 0
    },
    {
      "badge_color": "ff3618",
      "badge_name": "NEW",
      "description": "最高6个月免抽佣",
      "device": 0,
      "end_time": 0,
      "image_hash": "e91aa67f0eb852154c3a9d51e4b49034png",
      "is_show": 1,
      "key": " agent",
      "name": "城市代理申请",
      "schema": "eleme://web?url=https%3A%2F%2Fdaili.ele.me%2Fagent",
      "start_time": 0
    },
    {
      "badge_color": "ff3618",
      "badge_name": "HOT",
      "description": "低门槛极速放款",
      "device": 2,
      "end_time": 0,
      "image_hash": "b07f40331cbc42ec7354d024fdfbe813png",
      "is_show": 1,
      "key": "loan",
      "name": "我要借款",
      "schema": "eleme://web?url=https%3A%2F%2Floan-supermarket.faas.ele.me%2F%23%2F",
      "start_time": 0
    },
    {
      "badge_color": "",
      "badge_name": "",
      "description": "大额红包任性领",
      "device": 2,
      "end_time": 0,
      "image_hash": "05f108ca4e0c543488799f0c7c708cb1jpeg",
      "is_show": 1,
      "key": "game_center",
      "name": "玩游戏领红包",
      "schema": "eleme://web?url=https%3A%2F%2Fgamecenter.faas.ele.me",
      "start_time": 0
    },
    {
      "badge_color": "",
      "badge_name": "",
      "description": "每月最高500M",
      "device": 0,
      "end_time": 0,
      "image_hash": "9477abe3aebfe97a8d88576dcf281aafpng",
      "is_show": 1,
      "key": "transfer",
      "name": "免费流量",
      "schema": "eleme://web?url=https%3A%2F%2Fh5.ele.me%2Fesim%2F%23%2F&navType=2&navColor=%233072d4",
      "start_time": 0
    },
    {
      "badge_color": "",
      "badge_name": "",
      "description": "点餐也能做公益",
      "device": 0,
      "end_time": 0,
      "image_hash": "e2bf71f5f32b680132832f4c9b395fd5png",
      "is_show": 0,
      "key": "charity",
      "name": "饿公益",
      "schema": "eleme://web?url=https%3A%2F%2Fapp-resource.ele.me%2Fprod%2FrJM5Zvtyf.html&navType=0",
      "start_time": 0
    },
    {
      "badge_color": "",
      "badge_name": "",
      "description": "0元好物在这里",
      "device": 0,
      "end_time": 0,
      "image_hash": "6efcbf0a3d4148cc0f87965a59657dc2png",
      "is_show": 1,
      "key": "point",
      "name": "积分商城",
      "schema": "eleme://web?url=http%3A%2F%2Fm.maila88.com%2FmailaIndex%3FmailaAppKey%3DQZvmst1hqHnoubaiuho7wv",
      "start_time": 0
    },
    {
      "badge_color": "",
      "badge_name": "",
      "description": "",
      "device": 0,
      "end_time": 0,
      "image_hash": "3aaaed5a8f0a511f67da968ee3dad31epng",
      "is_show": 1,
      "key": "business_order",
      "name": "企业订餐",
      "schema": "eleme://web?url=https%3a%2f%2fentu.ele.me%2f%3ftype%3d4",
      "start_time": 0
    },
    {
      "badge_color": "",
      "badge_name": "",
      "description": "我的3小时我做主",
      "device": 0,
      "end_time": 0,
      "image_hash": "3240fe851ed58185097baabd864d64a0png",
      "is_show": 1,
      "key": "ali_public_welfare",
      "name": "3小时公益",
      "schema": "eleme://web?url=https%3a%2f%2f3hours.taobao.com",
      "start_time": 0
    }
  ],
  "delivery_card_expire_days": 0,
  "email": "",
  "gift_amount": 2, // 红包个数
  "is_email_valid": false,
  "is_mobile_valid": true,
  "mobile": "13812345678",
  "point": 0, // 金币个数
  "real_point": 0,
  "supervip_status": 1,
  "user_id": 1731112177,
  "username": "757f8734cc8"
}